APP_NAME = 'SFTP Auto Sync'
APP_SLUG = 'SFTPAutoSync'
SERVICE_NAME = 'sftp-auto-sync'

DEFAULT_PORT = 22
DEFAULT_CONNECT_TIMEOUT_SEC = 10
DEFAULT_DEBOUNCE_MS = 800
DEFAULT_AGGREGATOR_TICK_MS = 200
DEFAULT_STABILITY_CHECK_INTERVAL_MS = 300
DEFAULT_STABILITY_MAX_CHECKS = 5
DEFAULT_HISTORY_KEEP_ROWS = 20000
DEFAULT_MAX_RETRIES = 5
DEFAULT_RETRY_DELAYS = [1, 2, 5, 10, 20]
DEFAULT_LIVE_PRIORITY = 0
DEFAULT_RESCAN_PRIORITY = 10
DEFAULT_RETRY_PRIORITY = 20
LOG_MAX_BYTES = 5 * 1024 * 1024
LOG_BACKUP_COUNT = 5

SETTING_LOG_RETENTION_ROWS = 'log_retention_rows'
SETTING_DEBOUNCE_MS = 'debounce_ms'
SETTING_STARTUP_AUTO_START_ENGINE = 'startup_auto_start_engine'

DEFAULT_IGNORE_PATTERNS = [
    '.git/',
    '.idea/',
    '.vscode/',
    '.DS_Store',
    'Thumbs.db',
    '*.swp',
    '*.tmp',
    '*~',
]
